services:

  postgres:
    image: postgres:17

    container_name: job-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - job-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: job-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
    networks:
      - job-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend

    container_name: job-backend

    restart: unless-stopped

    env_file:
      - .env

    environment:
      REDIS_HOST: redis
      DB_HOST: postgres

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "5000:5000"

    networks:
      - job-network

  worker:
    build:
      context: ./backend
    restart: unless-stopped
    command: npm run start:worker
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - job-network
    deploy:
      replicas: 3

  dashboard:
    build:
      context: ./backend
    container_name: job-dashboard
    restart: unless-stopped
    command: npm run dashboard
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - job-network

  nginx:
    build:
      context: .
      dockerfile: infrastructure/nginx/Dockerfile

    container_name: job-nginx

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"
      - "443:443"

    networks:
      - job-network

    volumes:
      # Stores Let's Encrypt certificates
      - letsencrypt:/etc/letsencrypt

      # Used for ACME challenge
      - certbot-www:/var/www/certbot
  certbot:
    image: certbot/certbot

    container_name: job-certbot

    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot

networks:
  job-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  letsencrypt:
  certbot-www:
