const ROLES = {
  EMPLOYER: "EMPLOYER",
  CANDIDATE: "CANDIDATE",
};

const APPLICATION_STATUS = {
  PENDING: "PENDING",
  REVIEWED: "REVIEWED",
  INTERVIEW: "INTERVIEW",
  REJECTED: "REJECTED",
  HIRED: "HIRED",
};

const VALID_STATUS_TRANSITIONS = {
  PENDING: ["REVIEWED", "REJECTED"],

  REVIEWED: ["INTERVIEW", "REJECTED"],

  INTERVIEW: ["HIRED", "REJECTED"],

  REJECTED: [],

  HIRED: [],
};

module.exports = ROLES;
module.exports.APPLICATION_STATUS = APPLICATION_STATUS;
module.exports.VALID_STATUS_TRANSITIONS = VALID_STATUS_TRANSITIONS;
